apiVersion: v1
kind: Pod
metadata:
  labels:
    app: noodle
  name: noodle
spec:
  containers:
  - name: noodle
    image: us.gcr.io/letsbuild2020/letsbuild/noodle:dev
    imagePullPolicy: Always
    args:
    - entrypoint
    - --net
    - --boot
    - --start
    env:
    - name: NODE_ENV
      value: production
    - name: HOST
      value: 0.0.0.0
    - name: PORT
      value: "8080"
    - name: DB_CONNECTION
      value: mysql
    - name: DB_HOST
      value: remotemysql.com
    - name: DB_PORT
      value: "3306"
    - name: DB_USER
      value: onXA5z4GGx
    - name: DB_PASSWORD
      value: KQYKPeNiFT
    - name: DB_DATABASE
      value: onXA5z4GGx
    - name: APP_KEY
      value: Z1bwLiwKyGPn3yIALwuHQC4PyxdjQWl8
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        memory: 500Mi
      requests:
        memory: 300Mi
  imagePullSecrets:
  - name: gcr-json-key
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
